### ISSUE TITLE
more concise barrier.c

### ISSUE THREAD

**Issue by Winson-Huang** [xxyzz/ostep-hw#16]
In barrier.c at Chap 31(31/barrier.c), you use two variable in barrier_t, but I think you can just keep `num_threads`  and use `num_threads--;` when a thread enter barrier, then test `num_threads==0` . Besides, in fact test of `num_threads`  is not in critical section, so you can put `Sem_post(b->modCounter);` before the test.

**Comment by Winson-Huang** [comment]
If you like I can create a pr.

**Comment by xxyzz** [comment]
I put the test inside the mutex probably because the book(*The Little Book of Semaphores*) says it's usually not a good idea.

> If you like I can create a pr.

OK, please.
