### ISSUE TITLE
chapter 5 Q 2

### ISSUE THREAD

**Issue by songlin-zheng** [xxyzz/ostep-hw#4]
If you write open() before fork(), as indicated in the question, both processes will append to the end of th file, not overwrite.

**Comment by xxyzz** [comment]
I updated the answer in https://github.com/xxyzz/ostep-hw/commit/8fbf5e185da90cdd0c814074885a6eb171d59cb2. It depends on the scheduler, maybe they will write sequentially in most cases but not all the time.
