### ISSUE TITLE
Does chapter 8, question 5, have an incorrect answer?

### ISSUE THREAD

**Issue by modulitos** [xxyzz/ostep-hw#5]
First, I just want to say thanks for sharing your solutions 🎉  This is a great resources as I'm working through these exercises.

On [chapter 8, question 5](https://github.com/xxyzz/ostep-hw/blob/d4180a217d2be4f26a1f40d2366251efc3021913/8/README.md#questions), we have the following question:

>Given a system with a quantum length of 10ms in its highest queue, how often would you have to boost jobs back to the highest priority level (with the -B flag) in order to guarantee that a single long-running (and potentially-starving) job gets at least 5% of the CPU?

And it looks like your answer is 50ms, but shouldn't it be 200ms? It seems like 10ms will have to be 5% of the boost period.

So given a boost period B, I thought the equation would look like this:

> B * .05 = 10 ms

which makes B 200ms.

But maybe my answer is missing something? Perhaps there's an edge case where the 200ms boost period fails, but I can't think of one 🤔

**Comment by xxyzz** [comment]
You are right. I don't what I was thing back then. Thanks!

**Comment by modulitos** [comment]
Ah, good to know! Thanks for the quick response, and updating the repo 👍 

I'll close this issue now, since it's resolved
